spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pi-admin-test?characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    host: localhost
    password: 123456

logging:
  level:
    root: warn
    me.pi.admin: debug

flowable:
  async-executor-activate: false