spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://pi-db:3306/pi-admin?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: pi-redis
    password: 123456

logging:
  level:
    root: info
    me.pi.admin: debug

flowable:
  async-executor-activate: false

powerjob:
  worker:
    enabled: false
    app-name: pi-admin
    server-address: pi-powerjob:7700
    protocol: http
    max-result-length: 4096
    max-appended-wf-context-length: 4096
