spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pi-admin?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    password: 123456

logging:
  level:
    root: error
    me.pi.admin: info

flowable:
  database-schema-update: false

powerjob:
  worker:
    app-name: pi-admin
    server-address: localhost:7700
    protocol: http
    max-result-length: 4096
    max-appended-wf-context-length: 4096
