spring:
  datasource:
    url: jdbc:mysql://pi-db:3306/pi-admin?characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    host: pi-db
    password: 123456

logging:
  level:
    root: error
    me.pi.admin: info

flowable:
  database-schema-update: false
