version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pi-admin
    volumes:
      # 数据挂载
      - /docker/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /docker/mysql/conf/:/etc/mysql/conf.d/
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    privileged: true
    network_mode: "host"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      # 配置文件
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 前端代码
      - /docker/nginx/html:/usr/share/nginx/html
      # 日志
      - /docker/nginx/log:/var/log/nginx
    privileged: true
    network_mode: "host"

  redis:
    image: redis
    container_name: redis
    volumes:
      - /docker/redis/conf:/redis/config:rw
      - /docker/redis/data/:/redis/data/:rw
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    network_mode: "host"

  pi-admin-server1:
    image: pi/pi-admin:1.0.0-SNAPSHOT
    environment:
      SERVER_PORT: 9317
    volumes:
      - /docker/server1/logs/:/pi/server/logs
    privileged: true
    network_mode: "host"

  pi-admin-server2:
    image: pi/pi-admin:1.0.0-SNAPSHOT
    environment:
      SERVER_PORT: 9318
    volumes:
      - /docker/server2/logs/:/pi/server/logs
    privileged: true
    network_mode: "host"
